# Generated by Django 4.0.7 on 2022-09-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accessToken',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
