# Generated by Django 4.0 on 2023-03-20 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0011_2_7'),
        ('accounts', '0002_company_franchise_company_product'),
    ]

    operations = [        
        migrations.AlterField(
            model_name='company',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.price'),
        ),
    ]
