# Generated by Django 3.2.8 on 2023-05-12 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0011_2_7"),
        ("accounts", "0002_st_contacted"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="zapier_forSale",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="zapier_sold",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
