# Generated by Django 3.2.8 on 2023-03-25 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0011_2_7'),
        ('accounts', '0002_company_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='product',
            field=models.ForeignKey(blank=True, default=16, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.plan'),
        ),
    ]
