# Generated by Django 4.0 on 2023-03-01 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_client_company_alter_client_zipcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='client',
            name='zipCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.zipcode'),
        ),
        migrations.AlterField(
            model_name='clientupdate',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.client'),
        ),
        migrations.AlterField(
            model_name='homelisting',
            name='ScrapeResponse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.scraperesponse'),
        ),
        migrations.AlterField(
            model_name='homelisting',
            name='zipCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.zipcode'),
        ),
    ]
