# Generated by Django 3.2.8 on 2023-04-22 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0011_2_7'),
        ('accounts', '0003_company_sup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='sup',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.plan'),
        ),
    ]
