# Generated by Django 4.0 on 2023-03-02 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_client_company_alter_client_zipcode_and_more'),
    ]

    operations = [        
        migrations.RemoveField(
            model_name='client',
            name='company',
        ),
        migrations.RemoveField(
            model_name='client',
            name='zipCode',
        ),
        migrations.RemoveField(
            model_name='clientupdate',
            name='client',
        ),
        migrations.RemoveField(
            model_name='homelisting',
            name='ScrapeResponse',
        ),
        migrations.RemoveField(
            model_name='homelisting',
            name='zipCode',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='company',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.franchise'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ClientUpdate',
        ),
        migrations.DeleteModel(
            name='HomeListing',
        ),
        migrations.DeleteModel(
            name='ScrapeResponse',
        ),
        migrations.DeleteModel(
            name='ZipCode',
        ),
    ]
