# Generated by Django 3.2.8 on 2023-05-26 07:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230525_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='mainCompany',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_enterprise_owner',
            field=models.BooleanField(default=False),
        ),
    ]
