# Generated by Django 3.2.8 on 2023-04-22 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_company_sup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='sup',
            new_name='plan',
        ),
    ]
