# Generated by Django 4.0 on 2023-03-01 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company_franchise'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='client',
            name='company',
        ),
        migrations.RemoveField(
            model_name='client',
            name='zipCode',
        ),
        migrations.RemoveField(
            model_name='clientupdate',
            name='client',
        ),
        migrations.RemoveField(
            model_name='homelisting',
            name='ScrapeResponse',
        ),
        migrations.RemoveField(
            model_name='homelisting',
            name='zipCode',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ClientUpdate',
        ),
        migrations.DeleteModel(
            name='HomeListing',
        ),
        migrations.DeleteModel(
            name='ScrapeResponse',
        ),
        migrations.DeleteModel(
            name='ZipCode',
        ),
    ]
