# Generated by Django 3.2.8 on 2023-04-22 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_sup_company_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='plan',
            new_name='product',
        ),
    ]
