# Generated by Django 3.2.8 on 2023-05-26 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20230526_0753'),
        ('accounts', '0005_auto_20230526_0753'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Franchise',
        ),
        migrations.AddField(
            model_name='company',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='accounts.enterprise'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.enterprise'),
        ),
    ]
