# Generated by Django 3.2.8 on 2023-06-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_auto_20230526_0753"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="serviceTitanCustomerSyncOption",
            field=models.CharField(
                choices=[
                    ("option1", "option1"),
                    ("option2", "option2"),
                    ("option3", "option3"),
                ],
                default="option1",
                max_length=100,
            ),
        ),
    ]
