# Generated by Django 3.2.8 on 2023-06-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_company_servicetitancustomersyncoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='clientOption'
        ),
    ]
