# Generated by Django 3.2.8 on 2023-06-17 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0011_2_7"),
        ("accounts", "0008_company_zapier_recentlysold"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="product",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="djstripe.plan",
            ),
        ),
    ]
