# Generated by Django 3.2.8 on 2023-09-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_company_service_area_zip_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='service_titan_listed_date_custom_field_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='service_titan_sold_date_custom_field_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
