# Generated by Django 4.2.5 on 2023-10-20 05:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20230901_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='client_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None),
        ),
    ]
