# Generated by Django 4.2.5 on 2024-01-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_company_client_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='hubspot_api_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
