# Generated by Django 4.0.7 on 2022-09-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('zipCode', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('lastUpdated', models.DateField(default='2022-09-14')),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='accessToken',
            field=models.CharField(choices=[('test', 'test'), ('1qaz2wsx', '1qaz2wsx'), ('a29tp(u%hy@a5_p3x_d%!ct)m8r_@qj-skvksrz7id=k8nd9^m', 'a29tp(u%hy@a5_p3x_d%!ct)m8r_@qj-skvksrz7id=k8nd9^m')], max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(choices=[('test', 'test'), ('kinetico_knoxville', 'kinetico_knoxville'), ('isMyCustomerMoving', 'isMyCustomerMoving')], max_length=100),
        ),
    ]
