# Generated by Django 4.0.7 on 2022-09-14 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_zipcode_alter_company_accesstoken_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='zipCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.zipcode'),
        ),
    ]
