# Generated by Django 4.0.7 on 2022-09-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_client_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='lastUpdated',
            field=models.DateField(default='2022-09-13'),
        ),
    ]
