# Generated by Django 4.0.7 on 2022-09-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_homesale_homelisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='homelisting',
            name='status',
            field=models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent'), ('Recently Sold (6)', 'Recently Sold (6)'), ('Recently Sold (12)', 'Recently Sold (12)'), ('Off Market', 'Off Market'), ('No Change', 'No Change')], default='Off Market', max_length=20),
        ),
        migrations.DeleteModel(
            name='HomeSale',
        ),
    ]
