# Generated by Django 4.0.7 on 2022-09-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_homelisting_status_delete_homesale'),
    ]

    operations = [
        migrations.AddField(
            model_name='homelisting',
            name='listed',
            field=models.CharField(default='2022-09-15 01:08:05.414684', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('banned', 'BANNED'), ('admin', 'ADMIN')], default='active', max_length=100),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='lastUpdated',
            field=models.DateField(default='2022-09-14'),
        ),
    ]
