# Generated by Django 4.0.7 on 2022-09-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_homelisting_status_delete_homesale'),
    ]

    operations = [
        migrations.AddField(
            model_name='homelisting',
            name='listed',
            field=models.CharField(default='2022-09-14 21:34:12.894549', max_length=30),
        ),
    ]
