# Generated by Django 4.0.7 on 2022-09-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_customuser_status_alter_homelisting_listed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homelisting',
            name='listed',
            field=models.CharField(default='2022-09-15 00:06:00.262171', max_length=30),
        ),
    ]
