# Generated by Django 4.0.7 on 2022-09-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_homelisting_listed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homelisting',
            name='listed',
            field=models.CharField(default='2022-09-15 00:27:02.776342', max_length=30),
        ),
    ]
