# Generated by Django 4.0.7 on 2022-10-11 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_client_state_alter_homelisting_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email_frequency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='next_email_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 11, 4, 24, 18, 988741)),
        ),
        migrations.AlterField(
            model_name='homelisting',
            name='listed',
            field=models.CharField(default='2022-10-11 04:24:18.989554', max_length=30),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='lastUpdated',
            field=models.DateField(default='2022-10-10'),
        ),
    ]
