# Generated by Django 4.0.7 on 2022-10-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_client_contacted_client_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homelisting',
            name='listed',
            field=models.CharField(default='2022-10-11 06:44:26.987994', max_length=30),
        ),
    ]
