# Generated by Django 4.0.7 on 2022-11-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_homelisting_listed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='accessToken',
            field=models.CharField(default='xPg4vg1B9gVZMisL740CJ3U1oZ9RGGDM', max_length=32),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(choices=[('test', 'test'), ('kinetico_knoxville', 'kinetico_knoxville'), ('isMyCustomerMoving', 'isMyCustomerMoving'), ('Texas Water Specialist', 'Texas Water Specialist')], max_length=100),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='lastUpdated',
            field=models.DateField(default='2022-11-13'),
        ),
    ]
