# Generated by Django 4.0.7 on 2022-11-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_company_accesstoken_alter_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='accessToken',
            field=models.CharField(default='h52mviVNAWBrsTIri61ZelWFZW9PZPyg', max_length=32),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
