# Generated by Django 4.0.7 on 2022-11-18 16:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_company_accesstoken_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='accessToken',
            field=models.CharField(default='g0axKvkY1WanSYTpg9lyamTEtLJN6CWS', max_length=100),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='lastUpdated',
            field=models.DateField(default='2022-11-17'),
        ),
        migrations.CreateModel(
            name='InviteToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('expiration', models.DateTimeField(default=datetime.datetime(2022, 11, 19, 16, 36, 47, 790594, tzinfo=utc))),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
        ),
    ]
