# Generated by Django 4.0.7 on 2022-11-28 16:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_company_accesstoken_alter_zipcode_lastupdated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='accessToken',
            field=models.CharField(default='2r0Yd1UbD8ePOY6Z6pB3ipzy2ARPlrwS', max_length=100),
        ),
        migrations.AlterField(
            model_name='invitetoken',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 16, 10, 27, 318995, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='lastUpdated',
            field=models.DateField(default='2022-11-27'),
        ),
    ]
