# Generated by Django 4.0.7 on 2022-11-29 15:35

import accounts.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_company_accesstoken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='company',
            name='tier',
            field=models.CharField(choices=[('Free', 'Free'), ('Basic', 'Basic'), ('Premium', 'Premium'), ('Enterprise', 'Enterprise')], default='Free', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='accessToken',
            field=models.CharField(default=accounts.models.create_access_token, max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='next_email_date',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='invitetoken',
            name='expiration',
            field=models.DateTimeField(default=accounts.models.utc_tomorrow),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='lastUpdated',
            field=models.DateField(default='2022-11-28'),
        ),
    ]
