# Generated by Django 4.0.7 on 2022-11-28 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_remove_invitetoken_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitetoken',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 23, 4, 34, 47424)),
        ),
        migrations.AlterField(
            model_name='company',
            name='accessToken',
            field=models.CharField(default='4lkTPvdpQwNDwtcz35ctUrNWn79rbzuc', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='next_email_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 28, 23, 4, 34, 44396)),
        ),
    ]
