# Generated by Django 4.0.7 on 2022-12-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_remove_customuser_role_company_tier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='lastUpdated',
            field=models.DateField(default='2022-12-01'),
        ),
    ]
