# Generated by Django 4.0.7 on 2022-11-28 23:15

import accounts.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_invitetoken_expiration_alter_company_accesstoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='accessToken',
            field=models.CharField(default='uYM779504pgrHIaBCFg2PA6PUZ56Gl2j', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='next_email_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 28, 23, 15, 7, 362123)),
        ),
        migrations.AlterField(
            model_name='invitetoken',
            name='expiration',
            field=models.DateTimeField(default=accounts.models.utc_tomorrow),
        ),
    ]
