# Generated by Django 4.0.7 on 2022-12-02 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_name_product_tier'),
        ('accounts', '0038_alter_zipcode_lastupdated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='tier',
        ),
        migrations.AddField(
            model_name='company',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.product'),
        ),
    ]
