# Generated by Django 4.0.7 on 2022-11-28 23:16

import accounts.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_company_accesstoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='accessToken',
            field=models.CharField(default=accounts.models.create_access_token, max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='next_email_date',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
    ]
