# Generated by Django 4.0.7 on 2022-12-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tenantID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='lastUpdated',
            field=models.DateField(default='2022-12-15'),
        ),
    ]
