# Generated by Django 4.0.7 on 2022-12-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_company_tenantid_alter_zipcode_lastupdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='clientID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='clientSecret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='lastUpdated',
            field=models.DateField(default='2022-12-17'),
        ),
    ]
