# Generated by Django 4.0.7 on 2022-12-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_company_clientid_company_clientsecret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='servTitanID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
