# Generated by Django 4.0.7 on 2022-12-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_client_servtitanid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='lastUpdated',
            field=models.DateField(default='2022-12-30'),
        ),
    ]
