# Generated by Django 4.0.7 on 2022-12-31 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_alter_zipcode_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='zipCode',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
