# Generated by Django 4.0.7 on 2023-01-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_alter_zipcode_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('banned', 'BANNED'), ('admin', 'ADMIN'), ('pending', 'PENDING')], default='active', max_length=100),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='lastUpdated',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
