# Generated by Django 4.0.7 on 2023-01-02 18:20

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_alter_customuser_status_alter_zipcode_lastupdated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='lastUpdated',
            field=models.DateField(default=accounts.models.zipTime),
        ),
    ]
