# Generated by Django 4.0.7 on 2023-01-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_alter_zipcode_lastupdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stripeID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
