# Generated by Django 4.0.7 on 2023-01-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_company_stripeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='serviceTitanForRentTagID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='serviceTitanForSaleTagID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='serviceTitanRecentlySoldTagID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
