# Generated by Django 4.0.7 on 2023-01-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_rename_completed_task_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressupdate',
            name='tasks',
            field=models.IntegerField(default=0),
        ),
    ]
