# Generated by Django 4.0.7 on 2023-01-09 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_progressupdate_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='updater',
            field=models.ForeignKey(default='65b4881d-e3f6-47ed-b6af-f106068005fa', on_delete=django.db.models.deletion.CASCADE, to='accounts.progressupdate'),
            preserve_default=False,
        ),
    ]
