# Generated by Django 4.0.7 on 2023-01-12 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_clientupdate_delete_clientlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientupdate',
            name='listed',
            field=models.CharField(default=datetime.datetime.utcnow, max_length=30),
        ),
    ]
