# Generated by Django 4.0.7 on 2023-01-14 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_alter_clientupdate_listed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='allTimeForSaleCount',
        ),
        migrations.RemoveField(
            model_name='company',
            name='allTimeHomeSoldCount',
        ),
        migrations.AddField(
            model_name='clientupdate',
            name='contactValChanged',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='clientupdate',
            name='date',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
        migrations.AddField(
            model_name='clientupdate',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='clientupdate',
            name='listed',
            field=models.CharField(blank=True, default=datetime.datetime.utcnow, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clientupdate',
            name='status',
            field=models.CharField(blank=True, choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent'), ('Recently Sold (6)', 'Recently Sold (6)'), ('Recently Sold (12)', 'Recently Sold (12)'), ('Taken Off Market', 'Taken Off Market'), ('No Change', 'No Change')], default='No Change', max_length=20, null=True),
        ),
    ]
