# Generated by Django 4.0.7 on 2023-01-15 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_remove_clientupdate_contactvalchanged_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientupdate',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientupdate_set', to='accounts.client'),
        ),
    ]
