# Generated by Django 4.0.7 on 2023-01-15 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_alter_clientupdate_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientupdate',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientUpdates', to='accounts.client'),
        ),
    ]
