# Generated by Django 4.0.7 on 2023-01-16 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_client_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='avatarUrl',
        ),
        migrations.RemoveField(
            model_name='company',
            name='email_frequency',
        ),
        migrations.RemoveField(
            model_name='company',
            name='next_email_date',
        ),
    ]
