# Generated by Django 4.0.7 on 2023-01-16 15:12

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_remove_company_avatarurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientupdate',
            name='date',
            field=models.DateField(default=accounts.models.formatToday),
        ),
    ]
