# Generated by Django 4.0.7 on 2023-01-16 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_alter_clientupdate_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('company', 'name', 'address', 'zipCode')},
        ),
    ]
