# Generated by Django 4.1 on 2023-01-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0069_alter_client_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="complete",
        ),
        migrations.RemoveField(
            model_name="task",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="task",
            name="updater",
        ),
        migrations.AddField(
            model_name="task",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="client",
            unique_together={("company", "name", "address")},
        ),
        migrations.DeleteModel(
            name="ProgressUpdate",
        ),
    ]
