# Generated by Django 4.1 on 2023-01-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0070_remove_task_complete_remove_task_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="deletedClients",
            field=models.IntegerField(default=0),
        ),
    ]
