# Generated by Django 4.1 on 2023-01-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0072_alter_client_status_alter_clientupdate_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[
                    ("House For Sale", "House For Sale"),
                    ("House For Rent", "House For Rent"),
                    ("House Recently Sold (6)", "House Recently Sold (6)"),
                    ("Recently Sold (12)", "Recently Sold (12)"),
                    ("Taken Off Market", "Taken Off Market"),
                    ("No Change", "No Change"),
                ],
                db_index=True,
                default="No Change",
                max_length=25,
            ),
        ),
    ]
