# Generated by Django 4.1 on 2023-01-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0073_alter_client_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="city",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
