# Generated by Django 4.1 on 2023-01-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0074_alter_client_city"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="avatarUrl",
        ),
        migrations.AddField(
            model_name="customuser",
            name="otp_auth_url",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="otp_base32",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="otp_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="otp_verified",
            field=models.BooleanField(default=False),
        ),
    ]
