# Generated by Django 4.1 on 2023-01-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0075_remove_customuser_avatarurl_customuser_otp_auth_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientupdate",
            name="listed",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
