# Generated by Django 4.1 on 2023-01-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0076_alter_clientupdate_listed"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="validSubscription",
            field=models.BooleanField(default=True),
        ),
    ]
