# Generated by Django 4.1 on 2023-02-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0079_scraperesponse_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="note",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="otp_auth_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="otp_base32",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
