# Generated by Django 4.1 on 2023-02-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0080_alter_client_note_alter_customuser_otp_auth_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="crm",
            field=models.CharField(
                choices=[
                    ("ServiceTitan", "ServiceTitan"),
                    ("HubSpot", "HubSpot"),
                    ("Zoho", "Zoho"),
                    ("Salesforce", "Salesforce"),
                    ("FieldEdge", "FieldEdge"),
                    ("None", "None"),
                ],
                default="None",
                max_length=100,
            ),
        ),
    ]
