# Generated by Django 4.1 on 2023-02-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0081_company_crm"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="sfAccessToken",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
