# Generated by Django 4.1 on 2023-02-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0082_company_sfaccesstoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="sfRefreshToken",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
