# Generated by Django 4.0 on 2023-02-21 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0011_2_7'),
        ('accounts', '0083_company_sfrefreshtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.plan'),
        ),
    ]
