# Generated by Django 4.0 on 2023-02-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0083_company_sfrefreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
