# Generated by Django 4.0 on 2023-02-24 03:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0087_franchise_company_franchise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.franchise')),
                ('referredFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referredFrom', to='accounts.company')),
                ('referredTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referredTo', to='accounts.company')),
            ],
        ),
    ]
