# Generated by Django 4.0 on 2023-02-24 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0088_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referralClient', to='accounts.client'),
        ),
    ]
