# Generated by Django 4.0 on 2023-02-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0089_referral_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
    ]
