# Generated by Django 4.0 on 2023-02-27 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0090_referral_contacted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='franchise',
        ),
        migrations.RemoveField(
            model_name='company',
            name='product',
        ),
    ]
