# Generated by Django 3.2.8 on 2023-07-08 22:20

import data.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('data', '0001_initial'), ('data', '0002_alter_client_unique_together_referral'), ('data', '0003_homelistingtags_clientupdate_housingtype_and_more'), ('data', '0004_remove_clientupdate_housingtype_and_more'), ('data', '0005_alter_client_housingtype_alter_client_price_and_more'), ('data', '0006_client_equipmentinstalleddate'), ('data', '0007_homelisting_city_homelisting_state'), ('data', '0008_client_active'), ('data', '0009_alter_homelisting_unique_together'), ('data', '0010_alter_homelistingtags_tag'), ('data', '0011_auto_20230505_0014'), ('data', '0012_auto_20230516_0438'), ('data', '0013_auto_20230526_0753')]

    initial = True

    dependencies = [
        ('accounts', '0005_auto_20230526_0753'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=data.models.format_today)),
                ('response', models.TextField(default='')),
                ('zip', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('House For Sale', 'House For Sale'), ('House For Rent', 'House For Rent'), ('House Recently Sold (6)', 'House Recently Sold (6)'), ('Recently Sold (12)', 'Recently Sold (12)'), ('Taken Off Market', 'Taken Off Market'), ('No Change', 'No Change')], default='No Change', max_length=25, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('completed', models.BooleanField(default=False)),
                ('deletedClients', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('zipCode', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('lastUpdated', models.DateField(default=data.models.zip_time)),
            ],
        ),
        migrations.CreateModel(
            name='HomeListingTags',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tag', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('House For Sale', 'House For Sale'), ('House For Rent', 'House For Rent'), ('House Recently Sold (6)', 'House Recently Sold (6)'), ('Recently Sold (12)', 'Recently Sold (12)'), ('Taken Off Market', 'Taken Off Market'), ('No Change', 'No Change')], default='Off Market', max_length=25)),
                ('listed', models.CharField(default=' ', max_length=30)),
                ('ScrapeResponse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeListing_ScrapeResponse', to='data.scraperesponse')),
                ('zipCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeListing_zipCode', to='data.zipcode')),
                ('housingType', models.CharField(default=' ', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('year_built', models.IntegerField(default=0)),
                ('tag', models.ManyToManyField(blank=True, related_name='homeListing_tag', to='data.HomeListingTags')),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('state', models.CharField(blank=True, max_length=31, null=True)),
            ],
            options={
                'unique_together': {('address', 'status', 'city', 'state')},
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('House For Sale', 'House For Sale'), ('House For Rent', 'House For Rent'), ('House Recently Sold (6)', 'House Recently Sold (6)'), ('Recently Sold (12)', 'Recently Sold (12)'), ('Taken Off Market', 'Taken Off Market'), ('No Change', 'No Change')], default='No Change', max_length=25)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('state', models.CharField(blank=True, max_length=31, null=True)),
                ('contacted', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('servTitanID', models.IntegerField(blank=True, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_company', to='accounts.company')),
                ('zipCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_zipCode', to='data.zipcode')),
                ('housingType', models.CharField(blank=True, default=' ', max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('tag', models.ManyToManyField(blank=True, related_name='client_tags', to='data.HomeListingTags')),
                ('year_built', models.IntegerField(blank=True, default=0, null=True)),
                ('equipmentInstalledDate', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('error_flag', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('company', 'name', 'address')},
            },
        ),
        migrations.CreateModel(
            name='ClientUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=data.models.format_today)),
                ('status', models.CharField(blank=True, choices=[('House For Sale', 'House For Sale'), ('House For Rent', 'House For Rent'), ('House Recently Sold (6)', 'House Recently Sold (6)'), ('Recently Sold (12)', 'Recently Sold (12)'), ('Taken Off Market', 'Taken Off Market'), ('No Change', 'No Change')], default='No Change', max_length=25, null=True)),
                ('listed', models.CharField(blank=True, max_length=30, null=True)),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('contacted', models.BooleanField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientUpdates_client', to='data.client')),
                ('error_flag', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('contacted', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referralClient', to='data.client')),
                ('referredFrom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referredFrom', to='accounts.company')),
                ('referredTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referredTo', to='accounts.company')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.enterprise')),
            ],
        ),
    ]
