# Generated by Django 4.0 on 2023-02-27 05:02

import data.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('House For Sale', 'House For Sale'), ('House For Rent', 'House For Rent'), ('House Recently Sold (6)', 'House Recently Sold (6)'), ('Recently Sold (12)', 'Recently Sold (12)'), ('Taken Off Market', 'Taken Off Market'), ('No Change', 'No Change')], db_index=True, default='No Change', max_length=25)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('state', models.CharField(blank=True, max_length=31, null=True)),
                ('contacted', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('servTitanID', models.IntegerField(blank=True, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=data.models.formatToday)),
                ('response', models.TextField(default='')),
                ('zip', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('House For Sale', 'House For Sale'), ('House For Rent', 'House For Rent'), ('House Recently Sold (6)', 'House Recently Sold (6)'), ('Recently Sold (12)', 'Recently Sold (12)'), ('Taken Off Market', 'Taken Off Market'), ('No Change', 'No Change')], default='No Change', max_length=25, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('completed', models.BooleanField(default=False)),
                ('deletedClients', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('zipCode', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('lastUpdated', models.DateField(default=data.models.zipTime)),
            ],
        ),
        migrations.CreateModel(
            name='HomeListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('House For Sale', 'House For Sale'), ('House For Rent', 'House For Rent'), ('House Recently Sold (6)', 'House Recently Sold (6)'), ('Recently Sold (12)', 'Recently Sold (12)'), ('Taken Off Market', 'Taken Off Market'), ('No Change', 'No Change')], default='Off Market', max_length=25)),
                ('listed', models.CharField(default=' ', max_length=30)),
                ('ScrapeResponse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.scraperesponse')),
                ('zipCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.zipcode')),
            ],
        ),
        migrations.CreateModel(
            name='ClientUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=data.models.formatToday)),
                ('status', models.CharField(blank=True, choices=[('House For Sale', 'House For Sale'), ('House For Rent', 'House For Rent'), ('House Recently Sold (6)', 'House Recently Sold (6)'), ('Recently Sold (12)', 'Recently Sold (12)'), ('Taken Off Market', 'Taken Off Market'), ('No Change', 'No Change')], default='No Change', max_length=25, null=True)),
                ('listed', models.CharField(blank=True, max_length=30, null=True)),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('contacted', models.BooleanField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientUpdates', to='data.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='zipCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.zipcode'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('company', 'name', 'address')},
        ),
    ]
