# Generated by Django 4.0 on 2023-03-01 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO data_zipCode 
            SELECT
                *                
            FROM
                accounts_zipCode;
        """, reverse_sql="""
            INSERT INTO accounts_zipCode 
            SELECT
                *
            FROM
                data_zipCode;
        """),
        
        migrations.RunSQL("""
            INSERT INTO data_client
            SELECT
                *
            FROM
                accounts_client;
        """, reverse_sql="""
            INSERT INTO accounts_client 
            SELECT
                *
            FROM
                data_client;
        """),
        migrations.RunSQL("""
            INSERT INTO data_scraperesponse
            SELECT
                *
            FROM
                accounts_scraperesponse;
        """, reverse_sql="""
            INSERT INTO accounts_scraperesponse 
            SELECT
                *
            FROM
                data_scraperesponse;
        """),
        migrations.RunSQL("""
            INSERT INTO data_clientupdate 
            SELECT
                *
            FROM
                accounts_clientupdate;
        """, reverse_sql="""
            INSERT INTO accounts_clientupdate             
            SELECT
                *
            FROM
                data_clientupdate;
        """),
        migrations.RunSQL("""
            INSERT INTO data_task 
            SELECT
                *
            FROM
                accounts_task;
        """, reverse_sql="""
            INSERT INTO accounts_task 
            SELECT
                *
            FROM
                data_task;
        """),
        migrations.RunSQL("""
            INSERT INTO data_homelisting 
            SELECT
                *
            FROM
                accounts_homelisting;
        """, reverse_sql="""
            INSERT INTO accounts_homelisting
            SELECT
                *
            FROM
                data_homelisting;
        """)
    ]
