# Generated by Django 4.0 on 2023-03-01 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_client_unique_together_remove_client_company_and_more'),
        ('data', '0002_alter_client_unique_together_referral'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('company', 'name', 'address')},
        ),
    ]
