# Generated by Django 4.0 on 2023-03-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_homelistingtags_clientupdate_housingtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientupdate',
            name='housingType',
        ),
        migrations.RemoveField(
            model_name='clientupdate',
            name='price',
        ),
        migrations.RemoveField(
            model_name='clientupdate',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='clientupdate',
            name='year_built',
        ),
        migrations.AddField(
            model_name='client',
            name='housingType',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='client_tags', to='data.HomeListingTags'),
        ),
        migrations.AddField(
            model_name='client',
            name='year_built',
            field=models.IntegerField(default=0),
        ),
    ]
