# Generated by Django 4.0 on 2023-03-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_client_equipmentinstalleddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
