# Generated by Django 3.2.8 on 2023-04-30 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0008_client_active"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="homelisting",
            unique_together={("address", "status", "city", "state")},
        ),
    ]
