# Generated by Django 3.2.8 on 2023-05-26 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_auto_20230526_0753"),
        ("data", "0012_auto_20230516_0438"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referral",
            name="franchise",
        ),
        migrations.AddField(
            model_name="referral",
            name="enterprise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.enterprise",
            ),
        ),
    ]
