# Generated by Django 3.2.8 on 2023-07-08 22:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('data', '0014_client_revenue'), ('data', '0015_client_servicetitancustomersince'), ('data', '0016_auto_20230611_2026'), ('data', '0017_auto_20230611_2204'), ('data', '0018_homelisting_realtor'), ('data', '0019_client_usps_address'), ('data', '0020_client_usps_different'), ('data', '0021_savedfilter'), ('data', '0022_savedfilter_savedfilters'), ('data', '0023_auto_20230622_1759'), ('data', '0024_auto_20230628_1616'), ('data', '0025_alter_savedfilter_unique_together_and_more'), ('data', '0026_auto_20230706_1457')]

    dependencies = [
        ('accounts', '0010_auto_20230622_1758'),
        ('accounts', '0008_company_zapier_recentlysold'),
        ('data', '0013_auto_20230526_0753'),
        ('accounts', '0011_company_for_sale_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='revenue',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='homelisting',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homelisting',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homelisting',
            name='permalink',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='homelisting',
            name='cooling',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homelisting',
            name='description',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AddField(
            model_name='homelisting',
            name='exterior',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homelisting',
            name='fireplace',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homelisting',
            name='garage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='homelisting',
            name='garage_type',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homelisting',
            name='heating',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homelisting',
            name='pool',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homelisting',
            name='roofing',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homelisting',
            name='year_renovated',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='usps_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='usps_different',
            field=models.BooleanField(default=False),
        ),
        migrations.RenameField(
            model_name='client',
            old_name='equipmentInstalledDate',
            new_name='equipment_installed_date',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='housingType',
            new_name='housing_type',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='servTitanID',
            new_name='serv_titan_id',
        ),
        migrations.AddField(
            model_name='client',
            name='service_titan_customer_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='task',
            old_name='deletedClients',
            new_name='deleted_clients',
        ),
        migrations.RenameField(
            model_name='zipcode',
            old_name='lastUpdated',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='zipcode',
            old_name='zipCode',
            new_name='zip_code',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='zipCode',
            new_name='zip_code',
        ),
        migrations.RenameField(
            model_name='homelisting',
            old_name='housingType',
            new_name='housing_type',
        ),
        migrations.RenameField(
            model_name='homelisting',
            old_name='zipCode',
            new_name='zip_code',
        ),
        migrations.RenameField(
            model_name='referral',
            old_name='referredFrom',
            new_name='referred_from',
        ),
        migrations.RenameField(
            model_name='referral',
            old_name='referredTo',
            new_name='referred_to',
        ),
        migrations.AlterField(
            model_name='clientupdate',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_updates_client', to='data.client'),
        ),
        migrations.AddField(
            model_name='homelisting',
            name='bathrooms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='homelisting',
            name='bedrooms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='homelisting',
            name='lot_sqft',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='homelisting',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='homelisting',
            name='realtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_listing_realtor', to='data.realtor'),
        ),
        migrations.AddField(
            model_name='homelisting',
            name='sqft',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='homelisting',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='home_listing_tag', to='data.HomeListingTags'),
        ),
        migrations.AlterField(
            model_name='homelisting',
            name='year_built',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_client', to='data.client'),
        ),
        migrations.RemoveField(
            model_name='homelisting',
            name='ScrapeResponse',
        ),
        migrations.AlterField(
            model_name='client',
            name='zip_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_zip_code', to='data.zipcode'),
        ),
        migrations.AlterField(
            model_name='homelisting',
            name='housing_type',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homelisting',
            name='zip_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_listing_zip_code', to='data.zipcode'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referred_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_from', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referred_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_to', to='accounts.company'),
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('service_titan_tag', models.IntegerField(blank=True, null=True)),
                ('for_zapier', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('saved_filters', models.CharField(blank=True, max_length=1000, null=True)),
                ('filter_type', models.CharField(choices=[('Recently Sold', 'Recently Sold'), ('For Sale', 'For Sale'), ('Client', 'Client')], default='Client', max_length=25)),
            ],
            options={
                'unique_together': {('name', 'company', 'filter_type')},
            },
        ),
        migrations.AddField(
            model_name='client',
            name='bathrooms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='bedrooms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='lot_sqft',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='sqft',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clientupdate',
            name='contacted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='clientupdate',
            name='error_flag',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
