# Generated by Django 3.2.8 on 2023-09-01 23:01

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_client_revenue_squashed_0026_auto_20230706_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='email',
            new_name='agent_phone',
        ),
        migrations.RenameField(
            model_name='realtor',
            old_name='phone',
            new_name='brokerage_phone',
        ),
        # migrations.RemoveField(
        #     model_name='homelisting',
        #     name='permalink',
        # ),
        migrations.RemoveField(
            model_name='realtor',
            name='url',
        ),
        # migrations.AddField(
        #     model_name='client',
        #     name='new_city',
        #     field=models.CharField(blank=True, max_length=40, null=True),
        # ),
        # migrations.AddField(
        #     model_name='client',
        #     name='new_state',
        #     field=models.CharField(blank=True, max_length=31, null=True),
        # ),
        # migrations.AddField(
        #     model_name='client',
        #     name='new_zip_code',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
        #                             related_name='client_new_zip_code', to='data.zipcode'),
        # ),
        # migrations.AddField(
        #     model_name='client',
        #     name='service_titan_lifetime_revenue',
        #     field=models.FloatField(blank=True, default=0, null=True),
        # ),
        # migrations.RenameField(
        #     model_name='client',
        #     old_name='usps_address',
        #     new_name='old_address',
        # ),
        # migrations.AddField(
        #     model_name='homelisting',
        #     name='heating_cooling_description',
        #     field=models.TextField(blank=True, default=' ', null=True),
        # ),
        # migrations.AddField(
        #     model_name='homelisting',
        #     name='interior_features_description',
        #     field=models.TextField(blank=True, default=' ', null=True),
        # ),
        # migrations.AlterField(
        #     model_name='client',
        #     name='address',
        #     field=models.CharField(max_length=150),
        # ),
        # migrations.AddField(
        #     model_name='client',
        #     name='new_address',
        #     field=models.CharField(blank=True, max_length=150, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='client',
        #     name='old_address',
        #     field=models.CharField(blank=True, max_length=200, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='homelisting',
        #     name='address',
        #     field=models.CharField(max_length=150),
        # ),

        migrations.CreateModel(
            name='ServiceTitanJob',
            fields=[
                ('id', models.CharField(max_length=100,
                 primary_key=True, serialize=False)),
                ('job_type', models.CharField(max_length=100)),
                ('client', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='data.client')),
            ],
        ),
        migrations.AlterModelManagers(
            name='realtor',
            managers=[
                ('objects_with_listing_count', django.db.models.manager.Manager()),
            ],
        ),
    ]
