# Generated by Django 3.2.8 on 2023-07-13 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20230711_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='new_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='new_city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='new_state',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='new_zip_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_new_zip_code', to='data.zipcode'),
        ),
    ]
