# Generated by Django 3.2.8 on 2023-09-01 23:01

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20230711_1811_squashed_0023_alter_realtor_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
