# Generated by Django 4.2.5 on 2023-09-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
