# Generated by Django 3.2.8 on 2023-07-18 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_client_service_titan_lifetime_revenue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='usps_address',
            new_name='old_address',
        ),
    ]
