# Generated by Django 3.2.8 on 2023-06-11 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_auto_20230611_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='homelisting',
            name='realtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeListing_realtor', to='data.realtor'),
        ),
    ]
