# Generated by Django 4.2.5 on 2023-09-28 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_client_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='homelisting',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='client',
            name='usps_address',
        ),
        migrations.AddField(
            model_name='client',
            name='new_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='new_city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='new_state',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='new_zip_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='client_new_zip_code', to='data.zipcode'),
        ),
        migrations.AddField(
            model_name='client',
            name='old_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='service_titan_lifetime_revenue',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='homelisting',
            name='heating_cooling_description',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AddField(
            model_name='homelisting',
            name='interior_features_description',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('House For Sale', 'House For Sale'), ('Pending', 'Pending'), ('House Recently Sold (6)', 'House Recently Sold (6)'), (
                'House Recently Sold (12)', 'House Recently Sold (12)'), ('Off Market', 'Off Market')], default='No Change', max_length=25),
        ),
        migrations.AlterField(
            model_name='clientupdate',
            name='status',
            field=models.CharField(blank=True, choices=[('House For Sale', 'House For Sale'), ('Pending', 'Pending'), ('House Recently Sold (6)', 'House Recently Sold (6)'), (
                'House Recently Sold (12)', 'House Recently Sold (12)'), ('Off Market', 'Off Market')], default='No Change', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='homelisting',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='homelisting',
            name='status',
            field=models.CharField(choices=[('House For Sale', 'House For Sale'), ('Pending', 'Pending'), ('House Recently Sold (6)', 'House Recently Sold (6)'), (
                'House Recently Sold (12)', 'House Recently Sold (12)'), ('Off Market', 'Off Market')], default='Off Market', max_length=25),
        ),
        migrations.AlterField(
            model_name='scraperesponse',
            name='status',
            field=models.CharField(blank=True, choices=[('House For Sale', 'House For Sale'), ('Pending', 'Pending'), ('House Recently Sold (6)', 'House Recently Sold (6)'), (
                'House Recently Sold (12)', 'House Recently Sold (12)'), ('Off Market', 'Off Market')], default='No Change', max_length=25, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='homelisting',
            unique_together={('address', 'city', 'state', 'description')},
        ),
        migrations.RemoveField(
            model_name='homelisting',
            name='permalink',
        ),
    ]
