# Generated by Django 4.2.5 on 2023-09-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_alter_homelisting_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homelisting',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
