# Generated by Django 3.2.8 on 2023-06-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_homelisting_realtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='usps_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
