# Generated by Django 3.2.8 on 2023-06-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_client_usps_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='usps_different',
            field=models.BooleanField(default=False),
        ),
    ]
