# Generated by Django 4.2.5 on 2023-10-05 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_delete_scraperesponse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='homelisting',
            unique_together={('address', 'city', 'state')},
        ),
    ]
