# Generated by Django 3.2.8 on 2023-08-24 16:25

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_auto_20230722_0048'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='realtor',
            managers=[
                ('objects_with_listing_count', django.db.models.manager.Manager()),
            ],
        ),
    ]
