# Generated by Django 4.2.5 on 2023-10-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_alter_homelisting_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='homelisting',
            name='tag',
        ),
        migrations.DeleteModel(
            name='HomeListingTags',
        ),
    ]
