# Generated by Django 3.2.8 on 2023-09-05 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_alter_realtor_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='email',
            new_name='agent_phone',
        ),
        migrations.RenameField(
            model_name='realtor',
            old_name='phone',
            new_name='brokerage_phone',
        ),
        migrations.RemoveField(
            model_name='homelisting',
            name='permalink',
        ),
        migrations.RemoveField(
            model_name='realtor',
            name='url',
        ),
    ]
