# Generated by Django 3.2.8 on 2023-06-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_savedfilter_savedfilters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homelisting',
            name='bathrooms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='homelisting',
            name='bedrooms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='homelisting',
            name='lot_sqft',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='homelisting',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='homelisting',
            name='sqft',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='homelisting',
            name='year_built',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
