# Generated by Django 3.2.8 on 2023-06-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_auto_20230616_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='homelisting',
            name='heatingCoolingDescription',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AddField(
            model_name='homelisting',
            name='interiorFeaturesDescription',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
