# Generated by Django 4.2.5 on 2023-10-20 02:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_remove_client_tag_remove_homelisting_tag_client_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None),
        ),
    ]
