# Generated by Django 3.2.8 on 2023-06-28 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20230622_1758'),
        ('data', '0023_auto_20230622_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homelisting',
            name='ScrapeResponse',
        ),
        migrations.AlterField(
            model_name='client',
            name='zip_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_zip_code', to='data.zipcode'),
        ),
        migrations.AlterField(
            model_name='homelisting',
            name='housing_type',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homelisting',
            name='zip_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_listing_zip_code', to='data.zipcode'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referred_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_from', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referred_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_to', to='accounts.company'),
        ),
    ]
