# Generated by Django 3.2.8 on 2023-07-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_alter_savedfilter_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientupdate',
            name='contacted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='clientupdate',
            name='error_flag',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
