# Generated by Django 4.2.5 on 2023-10-20 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_alter_homelisting_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homelisting',
            name='cooling',
        ),
        migrations.RemoveField(
            model_name='homelisting',
            name='exterior',
        ),
        migrations.RemoveField(
            model_name='homelisting',
            name='fireplace',
        ),
        migrations.RemoveField(
            model_name='homelisting',
            name='garage_type',
        ),
        migrations.RemoveField(
            model_name='homelisting',
            name='heating',
        ),
        migrations.RemoveField(
            model_name='homelisting',
            name='heating_cooling_description',
        ),
        migrations.RemoveField(
            model_name='homelisting',
            name='interior_features_description',
        ),
        migrations.RemoveField(
            model_name='homelisting',
            name='pool',
        ),
        migrations.RemoveField(
            model_name='homelisting',
            name='realtor',
        ),
        migrations.RemoveField(
            model_name='homelisting',
            name='roofing',
        ),
    ]
