# Generated by Django 4.2.7 on 2024-01-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_client_client_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='customer_lifetime_value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='customer_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='hubspot_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
