web: gunicorn config.wsgi
release: python manage.py migrate
worker: REMAP_SIGTERM=SIGQUIT celery -A config worker -l INFO
worker: celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
