# Generated by Django 3.2.8 on 2023-07-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0005_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0)),
                ('interval', models.CharField(choices=[('month', 'month'), ('year', 'year')], default='month', max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
