# Generated by Django 3.2.8 on 2023-07-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_client_revenue_squashed_0026_auto_20230706_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='homelisting',
            name='heatingCoolingDescription',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AddField(
            model_name='homelisting',
            name='interiorFeaturesDescription',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
