# Generated by Django 3.2.8 on 2023-07-20 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_rename_usps_address_client_old_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homelisting',
            old_name='heatingCoolingDescription',
            new_name='heating_cooling_description',
        ),
        migrations.RenameField(
            model_name='homelisting',
            old_name='interiorFeaturesDescription',
            new_name='interior_features_description',
        ),
    ]
