# Generated by Django 3.2.8 on 2023-07-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_auto_20230720_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='new_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='old_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homelisting',
            name='address',
            field=models.CharField(max_length=150),
        ),
    ]
