# Generated by Django 3.2.8 on 2023-06-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0021_savedfilter"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedfilter",
            name="savedFilters",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
