# Generated by Django 3.2.8 on 2023-09-01 22:59

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_servicetitanjob'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='realtor',
            managers=[
                ('objects_with_listing_count', django.db.models.manager.Manager()),
            ],
        ),
    ]
