# Generated by Django 3.2.8 on 2023-06-22 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_auto_20230622_1758"),
        ("data", "0022_savedfilter_savedfilters"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="equipmentInstalledDate",
            new_name="equipment_installed_date",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="housingType",
            new_name="housing_type",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="phoneNumber",
            new_name="phone_number",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="servTitanID",
            new_name="serv_titan_id",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="serviceTitanCustomerSince",
            new_name="service_titan_customer_since",
        ),
        migrations.RenameField(
            model_name="savedfilter",
            old_name="forExistingClient",
            new_name="for_existing_client",
        ),
        migrations.RenameField(
            model_name="savedfilter",
            old_name="forZapier",
            new_name="for_zapier",
        ),
        migrations.RenameField(
            model_name="savedfilter",
            old_name="savedFilters",
            new_name="saved_filters",
        ),
        migrations.RenameField(
            model_name="savedfilter",
            old_name="serviceTitanTag",
            new_name="service_titan_tag",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="deletedClients",
            new_name="deleted_clients",
        ),
        migrations.RenameField(
            model_name="zipcode",
            old_name="lastUpdated",
            new_name="last_updated",
        ),
        migrations.RenameField(
            model_name="zipcode",
            old_name="zipCode",
            new_name="zip_code",
        ),
        migrations.RenameField(
            model_name="client", old_name="zipCode", new_name="zip_code"
        ),
        migrations.RenameField(
            model_name="homelisting",
            old_name="housingType",
            new_name="housing_type",
        ),
        migrations.RenameField(
            model_name="homelisting",
            old_name="zipCode",
            new_name="zip_code",
        ),
        migrations.RenameField(
            model_name="referral",
            old_name="referredFrom",
            new_name="referred_from",
        ),
        migrations.RenameField(
            model_name="referral",
            old_name="referredTo",
            new_name="referred_to",
        ),
        migrations.AlterField(
            model_name="clientupdate",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_updates_client",
                to="data.client",
            ),
        ),
        migrations.AlterField(
            model_name="homelisting",
            name="bathrooms",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="homelisting",
            name="bedrooms",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="homelisting",
            name="lot_sqft",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="homelisting",
            name="price",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="homelisting",
            name="realtor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="home_listing_realtor",
                to="data.realtor",
            ),
        ),
        migrations.AlterField(
            model_name="homelisting",
            name="sqft",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="homelisting",
            name="tag",
            field=models.ManyToManyField(
                blank=True,
                related_name="home_listing_tag",
                to="data.HomeListingTags",
            ),
        ),
        migrations.AlterField(
            model_name="homelisting",
            name="year_built",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="referral",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referral_client",
                to="data.client",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="savedfilter",
            unique_together={("name", "company", "for_existing_client")},
        ),
    ]
