# Generated by Django 4.2.2 on 2023-06-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_company_for_sale_purchased'),
        ('data', '0024_auto_20230628_1616'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedfilter',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='savedfilter',
            name='filter_type',
            field=models.CharField(choices=[('Recently Sold', 'Recently Sold'), ('For Sale', 'For Sale'), ('Client', 'Client')], default='Client', max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='savedfilter',
            unique_together={('name', 'company', 'filter_type')},
        ),
        migrations.RemoveField(
            model_name='savedfilter',
            name='for_existing_client',
        ),
    ]
