# Generated by Django 3.2.8 on 2023-07-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('payments', '0001_initial'), ('payments', '0002_rename_name_product_tier'), ('payments', '0003_product_customerlimit'), ('payments', '0004_product_realestateaddon'), ('payments', '0005_delete_product'), ('payments', '0006_product')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0)),
                ('interval', models.CharField(choices=[('month', 'month'), ('year', 'year')], default='month', max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
