# Generated by Django 4.0.7 on 2022-12-02 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="name",
            new_name="tier",
        ),
    ]
