# Generated by Django 3.2.8 on 2023-07-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_servicetitaninvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetitaninvoice',
            name='street',
        ),
    ]
