# Generated by Django 4.1 on 2023-02-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_product_customerlimit"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="realEstateAddOn",
            field=models.BooleanField(default=False),
        ),
    ]
