# Generated by Django 4.2.5 on 2023-09-18 19:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20230721_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetitaninvoice',
            name='invoice_id',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicetitaninvoice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
