# Generated by Django 4.0 on 2023-03-16 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_product_realestateaddon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
