# Generated by Django 4.2.7 on 2024-01-07 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_client_client_tags'),
        ('payments', '0004_servicetitaninvoice_invoice_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceTitanInvoice',
            new_name='CRMInvoice',
        ),
    ]
