export const LIST_REQUEST = 'LIST_REQUEST';
export const LIST_SUCCESS = 'LIST_SUCCESS';
export const LIST_FAIL = 'LIST_FAIL';
export const LIST_RESET = 'LIST_RESET';

export const UPLOAD_REQUEST = 'UPLOAD_REQUEST';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_FAIL = 'UPLOAD_FAIL';
export const UPLOAD_RESET = 'UPLOAD_RESET';

export const STATUS_REQUEST = 'STATUS_REQUEST';
export const STATUS_SUCCESS = 'STATUS_SUCCESS';
export const STATUS_FAIL = 'STATUS_FAIL';
export const STATUS_RESET = 'STATUS_RESET';

export const ADDUSER_REQUEST = 'ADDUSER_REQUEST';
export const ADDUSER_SUCCESS = 'ADDUSER_SUCCESS';
export const ADDUSER_FAIL = 'ADDUSER_FAIL';

export const NOTE_REQUEST = 'NOTE_REQUEST';
export const NOTE_SUCCESS = 'NOTE_SUCCESS';
export const NOTE_FAIL = 'NOTE_FAIL';

